# Generated by Django 4.1.3 on 2022-12-10 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categories', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 16, 29, 22, 52572)),
        ),
        migrations.AlterField(
            model_name='product',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 16, 29, 22, 52584)),
        ),
    ]
